### ISSUE TITLE
Destructuring Props life hack :D

### ISSUE THREAD

**Issue by Sara-Samer** [abdelrahmanfekri/udemy-copy-with-react#1]
https://github.com/abdelrahmanfekri/udemy-copy-with-react/blob/861b68bcd4196c5adf3a868ecc8bbd8d0d0a8b1f/src/components/Card.js#L4-L24

refer to [this](https://www.javaguides.net/2020/08/reactjs-tutorial-for-beginners-10-destructuring-props-and-states.html#:~:text=There%20are%20two%20ways%20to%20destructure%20props%20in%20a%20functional%20component%20the%20first%20way%20is%20destructuring%20it%20in%20the%20function%20parameter%20itself%3A)

**Comment by abdelrahmanfekri** [comment]
thanks a lot this helped me
